version: '3.8'

services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=Tienda
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=Tienda
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PORT=3306
    ports:
      - 3308:3308
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_HOSTS=mysql
    ports:
      - 8080:80
